name: Node JS CICD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_nodejs_app:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Set Up Node.js 22
        uses: actions/setup-node@v4
        with: 
          node-version: "22"

      - name: Install Dependencies
        run: npm install

      - name: Build Application   
        run: echo "Building application" #not working because of no provision for build script in package
     
      - name: Run ESlint
        run: echo "running lint" 

      - name: Run Unit Test
        run: echo "Running Unit Tests" 

        #Deploy using docker
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker Image
        run: docker build -t my-nodejs-app .

      - name: Tag Docker Images
        run: docker tag my-nodejs-app:latest  ${{ secrets.DOCKER_HUB_USERNAME }}/my-nodejs-app:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-nodejs-app:latest
        #Deploy to the server
      - name:  Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod  400 ~/.ssh/id_rsa

      - name: Add Known hosts
        run: ssh-keyscan -t rsa ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts  

      - name: Deploy To Production Server 
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} << 'EOF' 
          sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-nodejs-app:latest
          sudo docker stop my-nodejs-app || true
          sudo docker run my-nodejs-app || true
          sudo docker run -d -p 80:3000 --name my-nodejs-app ${{ secrets.DOCKER_HUB_USERNAME }}/my-nodejs-app:latest
          EOF