name: Node JS CI/CD Pipeline

on:
  push:
    branches:
      -master

jobs:
  build_nodejs_app:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkouts@v4

      - name: Set Up Node.js 22
        uses: actions/setup-node@v4
        with: 
          node-version: "22"

      - name: Install Dependencies
        run: npm install

      - name: Build Application     
        run: npm run build

      - name: Run ESlint
        run: npm run lint

       




